# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utgifter', '0003_auto_20171130_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='payment date')),
                ('floor', models.IntegerField(choices=[(1, 'Første etasje'), (2, 'Annen etasje')], default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
